# Generated by Django 4.2.6 on 2023-10-09 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_alter_user_managers_alter_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoteModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('periority', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'active'), ('hidden', 'hidden'), ('deactive', 'deactive')], default='deactive', max_length=20)),
                ('show', models.BooleanField(default=True)),
                ('duedate', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('alerttime', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('allowed_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            options={
                'verbose_name': 'Note',
            },
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('political', 'political'), ('social', 'social'), ('economic', 'economic'), ('sports', 'sports')], default='social', max_length=20)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.notemodel')),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('image', 'image'), ('voice', 'voice'), ('video', 'video')], default='image', max_length=20)),
                ('path', models.ImageField(upload_to='')),
                ('size', models.CharField(blank=True, max_length=20)),
                ('note', models.ManyToManyField(to='app.notemodel')),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('star', models.FloatField(default=0)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=20)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.notemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
            bases=('app.basemodel',),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.basemodel')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.notemodel')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.category')),
            ],
            bases=('app.basemodel',),
        ),
    ]
